export const categories: string[] = [
  "Power Sources",
  "Switchgear",
  "Transformers",
  "Loads",
  "Protection",
  "Connections",
];

export const symbolRegistry: Record<string, any> = {
  // --- Power Sources ---
  generator: {
    id: "generator",
    category: "Power Sources",
    displayName: "Generator",
    type: "symbol",
    symbolType: "generator",
    width: 60,
    height: 60,
    customData: { label: "G" },
  },
  motor: {
    id: "motor",
    category: "Power Sources",
    displayName: "Motor",
    type: "symbol",
    symbolType: "motor",
    width: 60,
    height: 60,
    customData: { label: "M" },
  },
  battery: {
    id: "battery",
    category: "Power Sources",
    displayName: "Battery",
    type: "symbol",
    symbolType: "battery",
    width: 40,
    height: 60,
  },
  solar_panel: {
    id: "solar_panel",
    category: "Power Sources",
    displayName: "Solar Panel",
    type: "symbol",
    symbolType: "solar_panel",
    width: 60,
    height: 60,
    customData: { label: "PV" },
  },

  // --- Switchgear ---
  circuit_breaker: {
    id: "circuit_breaker",
    category: "Switchgear",
    displayName: "Circuit Breaker",
    type: "symbol",
    symbolType: "circuit_breaker",
    width: 40,
    height: 60,
    customData: { label: "CB" },
  },
  disconnect_switch: {
    id: "disconnect_switch",
    category: "Switchgear",
    displayName: "Disconnect Switch",
    type: "symbol",
    symbolType: "disconnect_switch",
    width: 40,
    height: 60,
  },
  fuse: {
    id: "fuse",
    category: "Switchgear",
    displayName: "Fuse",
    type: "symbol",
    symbolType: "fuse",
    width: 30,
    height: 60,
  },
  contactor: {
    id: "contactor",
    category: "Switchgear",
    displayName: "Contactor",
    type: "symbol",
    symbolType: "contactor",
    width: 40,
    height: 60,
    customData: { label: "K" },
  },

  // --- Transformers ---
  transformer: {
    id: "transformer",
    category: "Transformers",
    displayName: "Transformer",
    type: "symbol",
    symbolType: "transformer",
    width: 60,
    height: 80,
    customData: { label: "T" },
  },
  current_transformer: {
    id: "current_transformer",
    category: "Transformers",
    displayName: "Current Transformer",
    type: "symbol",
    symbolType: "current_transformer",
    width: 40,
    height: 40,
    customData: { label: "CT" },
  },

  // --- Loads ---
  resistor: {
    id: "resistor",
    category: "Loads",
    displayName: "Resistor",
    type: "symbol",
    symbolType: "resistor",
    width: 60,
    height: 30,
  },
  capacitor: {
    id: "capacitor",
    category: "Loads",
    displayName: "Capacitor",
    type: "symbol",
    symbolType: "capacitor",
    width: 40,
    height: 60,
  },
  inductor: {
    id: "inductor",
    category: "Loads",
    displayName: "Inductor",
    type: "symbol",
    symbolType: "inductor",
    width: 60,
    height: 30,
  },
  lamp: {
    id: "lamp",
    category: "Loads",
    displayName: "Lamp",
    type: "symbol",
    symbolType: "lamp",
    width: 40,
    height: 40,
    customData: { label: "L" },
  },

  // --- Protection ---
  relay: {
    id: "relay",
    category: "Protection",
    displayName: "Relay",
    type: "symbol",
    symbolType: "relay",
    width: 50,
    height: 50,
    customData: { label: "R" },
  },
  surge_arrester: {
    id: "surge_arrester",
    category: "Protection",
    displayName: "Surge Arrester",
    type: "symbol",
    symbolType: "surge_arrester",
    width: 30,
    height: 60,
  },

  // --- Connections ---
  busbar: {
    id: "busbar",
    category: "Connections",
    displayName: "Busbar",
    type: "symbol",
    symbolType: "busbar",
    width: 200,
    height: 10,
  },
  ground: {
    id: "ground",
    category: "Connections",
    displayName: "Ground",
    type: "symbol",
    symbolType: "ground",
    width: 30,
    height: 40,
  },
  junction: {
    id: "junction",
    category: "Connections",
    displayName: "Junction",
    type: "symbol",
    symbolType: "junction",
    width: 10,
    height: 10,
  },
};
