// src/lib/editor/symbols/registry.ts

export const categories: string[] = [
  "Power Sources", "Transformers", "Motors and Generators", "Connections and Lines",
  "Switches and Disconnectors", "Breakers and Protection", "Fuses",
  "Relays and Contactors", "Metering", "Indicators and Lamps", "Terminals and Connectors"
];

const sym = (id: string, category: string, displayName: string, symbolType: string, w: number, h: number, customData?: Record<string, string>, tab: string = "iec") => ({
  id, category, displayName, type: "symbol", symbolType, tab, width: w, height: h, defaultWidth: w, defaultHeight: h, ...(customData ? { customData } : {}),
});

export const SYMBOL_REGISTRY: Record<string, any> = {
  // ==========================================
  // --- Lines & Connections (Tab: lines) --- (66 items)
  // ==========================================
  line_h: sym("line_h", "Connections and Lines", "Horizontal Line", "line_h", 60, 10, {}, "lines"),
  line_v: sym("line_v", "Connections and Lines", "Vertical Line", "line_v", 10, 60, {}, "lines"),
  crossing_no_conn: sym("crossing_no_conn", "Connections and Lines", "Crossing (No Dot)", "crossing", 40, 40, {}, "lines"),
  crossing_straight: sym("crossing_straight", "Connections and Lines", "Straight Crossing", "crossing_straight", 40, 40, {}, "lines"),
  diagonal: sym("diagonal", "Connections and Lines", "Diagonal", "diagonal", 50, 50, {}, "lines"),
  diagonal_rev: sym("diagonal_rev", "Connections and Lines", "Diagonal Rev", "diagonal_rev", 50, 50, {}, "lines"),
  cross_x: sym("cross_x", "Connections and Lines", "Crossing X", "cross_x", 40, 40, {}, "lines"),
  rebar: sym("rebar", "Connections and Lines", "Rebar", "line_h", 60, 10, {}, "lines"),
  wire_junction_dot: sym("wire_junction_dot", "Connections and Lines", "Wire Junction Dot", "wire_junction", 40, 40, {}, "lines"),
  discontinuous: sym("discontinuous", "Connections and Lines", "Discontinuous Line", "discontinuous", 60, 10, {}, "lines"),
  connection_l: sym("connection_l", "Connections and Lines", "Connection L", "connection_l", 40, 40, {}, "lines"),
  connection_r: sym("connection_r", "Connections and Lines", "Connection R", "connection_r", 40, 40, {}, "lines"),
  connection_t: sym("connection_t", "Connections and Lines", "Connection T", "connection_t", 40, 40, {}, "lines"),
  connection_b: sym("connection_b", "Connections and Lines", "Connection B", "connection_b", 40, 40, {}, "lines"),
  three_conductors_pe: sym("three_conductors_pe", "Connections and Lines", "3 Cond + PE", "multiconductor_3pe", 40, 60, {}, "lines"),
  four_conductors: sym("four_conductors", "Connections and Lines", "4 Conductors", "multiconductor_4", 40, 60, {}, "lines"),
  four_conductors_pe: sym("four_conductors_pe", "Connections and Lines", "4 Cond + PE", "multiconductor_4pe", 40, 60, {}, "lines"),
  three_conductors_n: sym("three_conductors_n", "Connections and Lines", "3 Cond + Neutral", "multiconductor_3n", 40, 60, {}, "lines"),
  three_conductors_pe_n: sym("three_conductors_pe_n", "Connections and Lines", "3 Cond + PE + N", "multiconductor_3pen", 50, 60, {}, "lines"),
  two_conductors: sym("two_conductors", "Connections and Lines", "2 Conductors", "multiconductor_2", 40, 60, {}, "lines"),
  two_conductors_n: sym("two_conductors_n", "Connections and Lines", "2 Cond + Neutral", "multiconductor_2n", 40, 60, {}, "lines"),
  single_conductor: sym("single_conductor", "Connections and Lines", "1 Conductor", "multiconductor_1", 40, 60, {}, "lines"),
  neutral_conductor: sym("neutral_conductor", "Connections and Lines", "Neutral Conductor", "multiconductor_n", 40, 60, {}, "lines"),
  protective_earth: sym("protective_earth", "Connections and Lines", "Protective Earth (PE)", "multiconductor_pe", 40, 60, {}, "lines"),
  phase_neutral_cond: sym("phase_neutral_cond", "Connections and Lines", "Phase + Neutral", "multiconductor_pn", 40, 60, {}, "lines"),
  phase_pe_cond: sym("phase_pe_cond", "Connections and Lines", "Phase + PE", "multiconductor_ppe", 40, 60, {}, "lines"),
  busbar_1p: sym("busbar_1p", "Connections and Lines", "1-Phase Busbar", "line_h", 80, 20, { label: "1P Busbar" }, "lines"),
  busbar_3p: sym("busbar_3p", "Connections and Lines", "3-Phase Busbar", "line_h", 80, 20, { label: "3P Busbar" }, "lines"),
  busbar_3p_n: sym("busbar_3p_n", "Connections and Lines", "3-PH+N Busbar", "line_h", 80, 20, { label: "3P+N Busbar" }, "lines"),
  busbar_dc: sym("busbar_dc", "Connections and Lines", "DC Busbar", "line_h", 80, 20, { label: "DC Busbar" }, "lines"),
  busbar_pe: sym("busbar_pe", "Connections and Lines", "PE Busbar", "line_h", 80, 20, { label: "PE Busbar" }, "lines"),
  twisted_pair: sym("twisted_pair", "Connections and Lines", "Twisted Pair", "discontinuous", 60, 20, { label: "TP" }, "lines"),
  coaxial_cable: sym("coaxial_cable", "Connections and Lines", "Coaxial Cable", "line_h", 60, 20, { label: "Coax" }, "lines"),
  shielded_cable_2c: sym("shielded_cable_2c", "Connections and Lines", "2C Shielded", "multiconductor_2", 40, 60, { label: "Shielded" }, "lines"),
  shielded_cable_3c: sym("shielded_cable_3c", "Connections and Lines", "3C Shielded", "multiconductor_3n", 40, 60, { label: "Shielded" }, "lines"),
  shielded_cable_4c: sym("shielded_cable_4c", "Connections and Lines", "4C Shielded", "multiconductor_4", 40, 60, { label: "Shielded" }, "lines"),
  fiber_optic: sym("fiber_optic", "Connections and Lines", "Fiber Optic", "discontinuous", 60, 10, { label: "FO" }, "lines"),
  cable_xlpe: sym("cable_xlpe", "Connections and Lines", "XLPE Cable", "line_h", 60, 10, { label: "XLPE" }, "lines"),
  cable_pvc: sym("cable_pvc", "Connections and Lines", "PVC Cable", "line_h", 60, 10, { label: "PVC" }, "lines"),
  cable_lszh: sym("cable_lszh", "Connections and Lines", "LSZH Cable", "line_h", 60, 10, { label: "LSZH" }, "lines"),
  cable_swa: sym("cable_swa", "Connections and Lines", "SWA Armored Cable", "line_h", 60, 10, { label: "SWA" }, "lines"),
  cable_thhn: sym("cable_thhn", "Connections and Lines", "THHN Wire", "line_h", 60, 10, { label: "THHN" }, "lines"),
  cable_cat5e: sym("cable_cat5e", "Connections and Lines", "Cat5e Data", "discontinuous", 60, 10, { label: "Cat5e" }, "lines"),
  cable_cat6: sym("cable_cat6", "Connections and Lines", "Cat6 Data", "discontinuous", 60, 10, { label: "Cat6" }, "lines"),
  cable_cat6a: sym("cable_cat6a", "Connections and Lines", "Cat6A Data", "discontinuous", 60, 10, { label: "Cat6A" }, "lines"),
  plug_socket: sym("plug_socket", "Terminals and Connectors", "Plug and Socket", "plug_socket", 40, 60, {}, "lines"),
  connector_base_1: sym("connector_base_1", "Terminals and Connectors", "Connector Base 1", "connector_base", 30, 30, {}, "lines"),
  connector_base_2: sym("connector_base_2", "Terminals and Connectors", "Connector Base (Pin)", "connector_base_pin", 30, 30, {}, "lines"),
  connector_base_3: sym("connector_base_3", "Terminals and Connectors", "Connector Base (Soc)", "connector_base_soc", 30, 30, {}, "lines"),
  term_blk_1: sym("term_blk_1", "Terminals and Connectors", "Terminal Block 1-Way", "connector_base", 30, 30, { label: "TB1" }, "lines"),
  term_blk_2: sym("term_blk_2", "Terminals and Connectors", "Terminal Block 2-Way", "connector_base", 30, 50, { label: "TB2" }, "lines"),
  term_blk_3: sym("term_blk_3", "Terminals and Connectors", "Terminal Block 3-Way", "connector_base", 30, 70, { label: "TB3" }, "lines"),
  term_blk_4: sym("term_blk_4", "Terminals and Connectors", "Terminal Block 4-Way", "connector_base", 30, 90, { label: "TB4" }, "lines"),
  term_blk_5: sym("term_blk_5", "Terminals and Connectors", "Terminal Block 5-Way", "connector_base", 30, 110, { label: "TB5" }, "lines"),
  term_blk_earth: sym("term_blk_earth", "Terminals and Connectors", "Earth Terminal", "connector_base", 30, 30, { label: "PE" }, "lines"),
  socket_outlet_1p: sym("socket_outlet_1p", "Terminals and Connectors", "1P Socket Outlet", "connector_base_soc", 40, 40, { label: "1P" }, "lines"),
  socket_outlet_2p: sym("socket_outlet_2p", "Terminals and Connectors", "2P Socket Outlet", "connector_base_soc", 50, 40, { label: "2P" }, "lines"),
  socket_outlet_3p: sym("socket_outlet_3p", "Terminals and Connectors", "3P Socket Outlet", "connector_base_soc", 60, 40, { label: "3P" }, "lines"),
  socket_outlet_3pn: sym("socket_outlet_3pn", "Terminals and Connectors", "3P+N Socket Outlet", "connector_base_soc", 70, 40, { label: "3P+N" }, "lines"),

  // ==========================================
  // --- IEC Category --- (124 items)
  // ==========================================
  iec_cb_thermal: sym("iec_cb_thermal", "Breakers and Protection", "CB Thermal", "iec_cb_thermal", 40, 60, {}, "iec"),
  iec_cb_magnetic: sym("iec_cb_magnetic", "Breakers and Protection", "CB Magnetic", "iec_cb_magnetic", 40, 60, {}, "iec"),
  iec_cb_therm_mag: sym("iec_cb_therm_mag", "Breakers and Protection", "CB Therm-Mag", "iec_cb_therm_mag", 40, 60, {}, "iec"),
  mcb_1p_b: sym("mcb_1p_b", "Breakers and Protection", "1P MCB (Curve B)", "circuit_breaker", 40, 60, { label: "Type B" }, "iec"),
  mcb_1p_c: sym("mcb_1p_c", "Breakers and Protection", "1P MCB (Curve C)", "circuit_breaker", 40, 60, { label: "Type C" }, "iec"),
  mcb_1p_d: sym("mcb_1p_d", "Breakers and Protection", "1P MCB (Curve D)", "circuit_breaker", 40, 60, { label: "Type D" }, "iec"),
  mcb_2p_b: sym("mcb_2p_b", "Breakers and Protection", "2P MCB (Curve B)", "circuit_breaker_2p", 50, 60, { label: "Type B" }, "iec"),
  mcb_2p_c: sym("mcb_2p_c", "Breakers and Protection", "2P MCB (Curve C)", "circuit_breaker_2p", 50, 60, { label: "Type C" }, "iec"),
  mcb_2p_d: sym("mcb_2p_d", "Breakers and Protection", "2P MCB (Curve D)", "circuit_breaker_2p", 50, 60, { label: "Type D" }, "iec"),
  mcb_3p_b: sym("mcb_3p_b", "Breakers and Protection", "3P MCB (Curve B)", "circuit_breaker_3p", 60, 60, { label: "Type B" }, "iec"),
  mcb_3p_c: sym("mcb_3p_c", "Breakers and Protection", "3P MCB (Curve C)", "circuit_breaker_3p", 60, 60, { label: "Type C" }, "iec"),
  mcb_3p_d: sym("mcb_3p_d", "Breakers and Protection", "3P MCB (Curve D)", "circuit_breaker_3p", 60, 60, { label: "Type D" }, "iec"),
  mcb_4p_b: sym("mcb_4p_b", "Breakers and Protection", "4P MCB (Curve B)", "circuit_breaker_4p", 70, 60, { label: "Type B" }, "iec"),
  mcb_4p_c: sym("mcb_4p_c", "Breakers and Protection", "4P MCB (Curve C)", "circuit_breaker_4p", 70, 60, { label: "Type C" }, "iec"),
  mcb_4p_d: sym("mcb_4p_d", "Breakers and Protection", "4P MCB (Curve D)", "circuit_breaker_4p", 70, 60, { label: "Type D" }, "iec"),
  mccb_2p: sym("mccb_2p", "Breakers and Protection", "2P MCCB", "mccb", 50, 80, {}, "iec"),
  mccb_3p: sym("mccb_3p", "Breakers and Protection", "3P MCCB", "mccb", 60, 80, {}, "iec"),
  mccb_4p: sym("mccb_4p", "Breakers and Protection", "4P MCCB", "mccb", 70, 80, {}, "iec"),
  acb_3p: sym("acb_3p", "Breakers and Protection", "3P ACB", "acb", 70, 90, {}, "iec"),
  acb_4p: sym("acb_4p", "Breakers and Protection", "4P ACB", "acb", 80, 90, {}, "iec"),
  acb_drawout: sym("acb_drawout", "Breakers and Protection", "Drawout ACB", "acb", 70, 90, { label: "Drawout" }, "iec"),
  motor_circuit_brk: sym("motor_circuit_brk", "Breakers and Protection", "Motor CB", "motor_cb", 50, 70, {}, "iec"),
  rcbo_1p_iec: sym("rcbo_1p_iec", "Breakers and Protection", "1P+N RCBO", "rcbo", 50, 70, {}, "iec"),
  rcbo_2p_iec: sym("rcbo_2p_iec", "Breakers and Protection", "2P RCBO", "rcbo", 50, 70, {}, "iec"),
  rcbo_3p_iec: sym("rcbo_3p_iec", "Breakers and Protection", "3P RCBO", "rcbo", 60, 70, {}, "iec"),
  rcbo_4p_iec: sym("rcbo_4p_iec", "Breakers and Protection", "4P RCBO", "rcbo", 70, 70, {}, "iec"),
  rcd_2p: sym("rcd_2p", "Breakers and Protection", "2P RCD/RCCB", "rcbo", 50, 70, { label: "RCD" }, "iec"),
  rcd_4p: sym("rcd_4p", "Breakers and Protection", "4P RCD/RCCB", "rcbo", 70, 70, { label: "RCD" }, "iec"),
  elcb_3p: sym("elcb_3p", "Breakers and Protection", "3P ELCB", "rcbo", 60, 70, { label: "ELCB" }, "iec"),
  surge_arrester_1p: sym("surge_arrester_1p", "Breakers and Protection", "1P Surge Arrester", "surge_arrester", 40, 60, {}, "iec"),
  surge_arrester_2p: sym("surge_arrester_2p", "Breakers and Protection", "2P Surge Arrester", "surge_arrester", 50, 60, {}, "iec"),
  surge_arrester_3p: sym("surge_arrester_3p", "Breakers and Protection", "3P Surge Arrester", "surge_arrester", 60, 60, {}, "iec"),
  surge_arrester_4p: sym("surge_arrester_4p", "Breakers and Protection", "4P Surge Arrester", "surge_arrester", 70, 60, {}, "iec"),
  fuse_1p_iec: sym("fuse_1p_iec", "Fuses", "1P Fuse", "fuse", 20, 60, {}, "iec"),
  fuse_2p_iec: sym("fuse_2p_iec", "Fuses", "2P Fuse", "fuse_3p", 40, 60, {}, "iec"),
  fuse_3p_iec: sym("fuse_3p_iec", "Fuses", "3P Fuse", "fuse_3p", 60, 60, {}, "iec"),
  fuse_4p_iec: sym("fuse_4p_iec", "Fuses", "4P Fuse", "fuse_3p", 70, 60, {}, "iec"),
  fuse_nh_00: sym("fuse_nh_00", "Fuses", "NH00 Fuse", "fuse", 30, 60, { label: "NH00" }, "iec"),
  fuse_nh_1: sym("fuse_nh_1", "Fuses", "NH1 Fuse", "fuse", 35, 70, { label: "NH1" }, "iec"),
  fuse_disconnector_1p: sym("fuse_disconnector_1p", "Fuses", "1P Fuse Disc.", "fuse_disconnector", 40, 60, {}, "iec"),
  fuse_disconnector_3p: sym("fuse_disconnector_3p", "Fuses", "3P Fuse Disc.", "fuse_switch_disc_3", 60, 60, {}, "iec"),
  fuse_switch_disc_1p: sym("fuse_switch_disc_1p", "Fuses", "1P Fuse Sw. Disc.", "fuse_switch_disc", 40, 60, {}, "iec"),
  fuse_switch_disc_3p: sym("fuse_switch_disc_3p", "Fuses", "3P Fuse Sw. Disc.", "fuse_switch_disc_3", 60, 60, {}, "iec"),
  generator_ac_1p: sym("generator_ac_1p", "Power Sources", "1P AC Gen", "generator", 50, 50, { label: "1~" }, "iec"),
  generator_ac_3p: sym("generator_ac_3p", "Power Sources", "3P AC Gen", "generator", 50, 50, { label: "3~" }, "iec"),
  generator_dc: sym("generator_dc", "Power Sources", "DC Gen", "generator_dc", 50, 50, {}, "iec"),
  motor_ac_1p: sym("motor_ac_1p", "Motors and Generators", "1P AC Motor", "motor", 50, 50, { label: "1~" }, "iec"),
  motor_ac_3p: sym("motor_ac_3p", "Motors and Generators", "3P AC Motor", "motor_3p", 60, 50, {}, "iec"),
  motor_dc: sym("motor_dc", "Motors and Generators", "DC Motor", "motor_dc", 50, 50, {}, "iec"),
  motor_stepper: sym("motor_stepper", "Motors and Generators", "Stepper Motor", "motor", 50, 50, { label: "Step" }, "iec"),
  motor_servo: sym("motor_servo", "Motors and Generators", "Servo Motor", "motor", 50, 50, { label: "Servo" }, "iec"),
  iec_contact_no: sym("iec_contact_no", "Switches and Disconnectors", "Contact NO", "iec_contact_no", 40, 50, {}, "iec"),
  iec_contact_nc: sym("iec_contact_nc", "Switches and Disconnectors", "Contact NC", "iec_contact_nc", 40, 50, {}, "iec"),
  iec_contact_c_no_nc: sym("iec_contact_c_no_nc", "Switches and Disconnectors", "Contact C/NO/NC", "selector_switch_2", 40, 60, { label: "SPDT" }, "iec"),
  iec_pushbutton_no: sym("iec_pushbutton_no", "Switches and Disconnectors", "Pushbutton NO", "pushbutton_no", 40, 50, {}, "iec"),
  iec_pushbutton_nc: sym("iec_pushbutton_nc", "Switches and Disconnectors", "Pushbutton NC", "pushbutton_nc", 40, 50, {}, "iec"),
  iec_pushbutton_mush: sym("iec_pushbutton_mush", "Switches and Disconnectors", "Mushroom Head", "pushbutton_mush", 40, 50, {}, "iec"),
  iec_emergency_stop_no: sym("iec_emergency_stop_no", "Switches and Disconnectors", "E-Stop NO", "emergency_stop_no", 40, 50, {}, "iec"),
  iec_emergency_stop_nc: sym("iec_emergency_stop_nc", "Switches and Disconnectors", "E-Stop NC", "emergency_stop_nc", 40, 50, {}, "iec"),
  iec_limit_sw_no: sym("iec_limit_sw_no", "Switches and Disconnectors", "Limit Switch NO", "limit_switch_no", 40, 50, {}, "iec"),
  iec_limit_sw_nc: sym("iec_limit_sw_nc", "Switches and Disconnectors", "Limit Switch NC", "limit_switch_nc", 40, 50, {}, "iec"),
  iec_prox_sw_no: sym("iec_prox_sw_no", "Switches and Disconnectors", "Proximity NO", "prox_switch_no", 40, 50, {}, "iec"),
  iec_prox_sw_nc: sym("iec_prox_sw_nc", "Switches and Disconnectors", "Proximity NC", "prox_switch_nc", 40, 50, {}, "iec"),
  iec_prox_ind_no: sym("iec_prox_ind_no", "Switches and Disconnectors", "Inductive NO", "prox_switch_no", 40, 50, { label: "Ind" }, "iec"),
  iec_prox_cap_no: sym("iec_prox_cap_no", "Switches and Disconnectors", "Capacitive NO", "prox_switch_no", 40, 50, { label: "Cap" }, "iec"),
  iec_prox_opt_no: sym("iec_prox_opt_no", "Switches and Disconnectors", "Optical NO", "prox_switch_no", 40, 50, { label: "Opt" }, "iec"),
  iec_prox_ult_no: sym("iec_prox_ult_no", "Switches and Disconnectors", "Ultrasonic NO", "prox_switch_no", 40, 50, { label: "Us" }, "iec"),
  iec_flow_sw_no: sym("iec_flow_sw_no", "Switches and Disconnectors", "Flow Switch NO", "prox_switch_no", 40, 50, { label: "Flow" }, "iec"),
  iec_flow_sw_nc: sym("iec_flow_sw_nc", "Switches and Disconnectors", "Flow Switch NC", "prox_switch_nc", 40, 50, { label: "Flow" }, "iec"),
  iec_press_sw_no: sym("iec_press_sw_no", "Switches and Disconnectors", "Pressure Sw NO", "prox_switch_no", 40, 50, { label: "Press" }, "iec"),
  iec_press_sw_nc: sym("iec_press_sw_nc", "Switches and Disconnectors", "Pressure Sw NC", "prox_switch_nc", 40, 50, { label: "Press" }, "iec"),
  iec_temp_sw_no: sym("iec_temp_sw_no", "Switches and Disconnectors", "Temp Switch NO", "prox_switch_no", 40, 50, { label: "Temp" }, "iec"),
  iec_temp_sw_nc: sym("iec_temp_sw_nc", "Switches and Disconnectors", "Temp Switch NC", "prox_switch_nc", 40, 50, { label: "Temp" }, "iec"),
  iec_level_sw_no: sym("iec_level_sw_no", "Switches and Disconnectors", "Level Switch NO", "prox_switch_no", 40, 50, { label: "Level" }, "iec"),
  iec_level_sw_nc: sym("iec_level_sw_nc", "Switches and Disconnectors", "Level Switch NC", "prox_switch_nc", 40, 50, { label: "Level" }, "iec"),
  iec_gas_sw_no: sym("iec_gas_sw_no", "Switches and Disconnectors", "Gas Sensor NO", "prox_switch_no", 40, 50, { label: "Gas" }, "iec"),
  iec_selector_2: sym("iec_selector_2", "Switches and Disconnectors", "Selector 2-Pos", "selector_switch_2", 40, 50, {}, "iec"),
  iec_selector_3: sym("iec_selector_3", "Switches and Disconnectors", "Selector 3-Pos", "selector_switch_3", 40, 50, {}, "iec"),
  iec_key_sw_2: sym("iec_key_sw_2", "Switches and Disconnectors", "Key Switch 2P", "selector_switch_2", 40, 50, { label: "Key" }, "iec"),
  iec_key_sw_3: sym("iec_key_sw_3", "Switches and Disconnectors", "Key Switch 3P", "selector_switch_3", 40, 50, { label: "Key" }, "iec"),
  iec_switch_disc_1p: sym("iec_switch_disc_1p", "Switches and Disconnectors", "1P Disconnect", "disconnect_switch", 40, 60, {}, "iec"),
  iec_switch_disc_2p: sym("iec_switch_disc_2p", "Switches and Disconnectors", "2P Disconnect", "isolator_3p", 50, 60, { label: "2P" }, "iec"),
  iec_switch_disc_3p: sym("iec_switch_disc_3p", "Switches and Disconnectors", "3P Disconnect", "isolator_3p", 60, 60, {}, "iec"),
  iec_switch_disc_4p: sym("iec_switch_disc_4p", "Switches and Disconnectors", "4P Disconnect", "isolator_3p", 70, 60, { label: "4P" }, "iec"),
  iec_load_break_3p: sym("iec_load_break_3p", "Switches and Disconnectors", "3P Load Break", "switch_disconnector", 60, 60, {}, "iec"),
  iec_earthing_sw_1p: sym("iec_earthing_sw_1p", "Switches and Disconnectors", "1P Earth Switch", "earthing_disconnector", 40, 60, {}, "iec"),
  iec_earthing_sw_3p: sym("iec_earthing_sw_3p", "Switches and Disconnectors", "3P Earth Switch", "earthing_disconnector", 60, 60, { label: "3P" }, "iec"),
  contactor_1p: sym("contactor_1p", "Relays and Contactors", "1P Contactor", "contactor", 40, 50, {}, "iec"),
  contactor_2p: sym("contactor_2p", "Relays and Contactors", "2P Contactor", "contactor", 50, 50, { label: "2P" }, "iec"),
  contactor_3p: sym("contactor_3p", "Relays and Contactors", "3P Contactor", "contactor_3p", 60, 50, {}, "iec"),
  contactor_4p: sym("contactor_4p", "Relays and Contactors", "4P Contactor", "contactor_3p", 70, 50, { label: "4P" }, "iec"),
  iec_relay_coil: sym("iec_relay_coil", "Relays and Contactors", "Relay Coil", "relay_coil", 40, 40, {}, "iec"),
  iec_timer_coil: sym("iec_timer_coil", "Relays and Contactors", "Timer Coil", "timer_relay", 40, 40, {}, "iec"),
  iec_contactor_coil: sym("iec_contactor_coil", "Relays and Contactors", "Contactor Coil", "contactor_coil", 40, 50, {}, "iec"),
  overload_relay_1p: sym("overload_relay_1p", "Relays and Contactors", "1P Overload", "overload_relay", 40, 40, {}, "iec"),
  overload_relay_3p: sym("overload_relay_3p", "Relays and Contactors", "3P Overload", "overload_relay", 60, 40, { label: "3P-OL" }, "iec"),
  thermal_relay_iec: sym("thermal_relay_iec", "Relays and Contactors", "Thermal Relay", "thermal_relay", 40, 60, {}, "iec"),
  ssr_relay: sym("ssr_relay", "Relays and Contactors", "Solid State Relay", "contactor", 50, 50, { label: "SSR" }, "iec"),
  timer_on_delay: sym("timer_on_delay", "Relays and Contactors", "ON-Delay Timer", "timer_relay", 40, 40, { label: "TON" }, "iec"),
  timer_off_delay: sym("timer_off_delay", "Relays and Contactors", "OFF-Delay Timer", "timer_relay", 40, 40, { label: "TOFF" }, "iec"),
  timer_star_delta: sym("timer_star_delta", "Relays and Contactors", "Star-Delta Timer", "timer_relay", 40, 40, { label: "Y/D" }, "iec"),
  timer_flasher: sym("timer_flasher", "Relays and Contactors", "Flasher Timer", "timer_relay", 40, 40, { label: "Flasher" }, "iec"),
  transformer_iec: sym("transformer_iec", "Transformers", "1P Trafo (IEC)", "transformer", 40, 60, {}, "iec"),
  transformer_3p_iec: sym("transformer_3p_iec", "Transformers", "3P Trafo (IEC)", "transformer", 60, 60, { label: "3P" }, "iec"),
  transformer_3w_iec: sym("transformer_3w_iec", "Transformers", "3-Winding Trafo", "transformer_3w", 40, 80, {}, "iec"),
  auto_transformer: sym("auto_transformer", "Transformers", "Auto Transformer", "auto_transformer", 40, 60, {}, "iec"),
  potential_trans_1p: sym("potential_trans_1p", "Transformers", "1P PT", "potential_transformer", 40, 40, {}, "iec"),
  potential_trans_3p: sym("potential_trans_3p", "Transformers", "3P PT", "potential_transformer", 60, 40, { label: "3P" }, "iec"),
  current_trans_1p: sym("current_trans_1p", "Transformers", "1P CT", "current_transformer", 40, 40, {}, "iec"),
  current_trans_3p: sym("current_trans_3p", "Transformers", "3P CT", "current_transformer", 60, 40, { label: "3P" }, "iec"),
  lamp_iec: sym("lamp_iec", "Indicators and Lamps", "Lamp", "lamp", 40, 40, {}, "iec"),
  led_iec: sym("led_iec", "Indicators and Lamps", "LED", "lamp", 40, 40, { label: "LED" }, "iec"),
  buzzer_iec: sym("buzzer_iec", "Indicators and Lamps", "Buzzer", "lamp", 40, 40, { label: "Buzzer" }, "iec"),
  siren_iec: sym("siren_iec", "Indicators and Lamps", "Siren", "lamp", 40, 40, { label: "Siren" }, "iec"),
  resistor_iec: sym("resistor_iec", "Indicators and Lamps", "Resistor", "resistor", 60, 30, {}, "iec"),
  var_resistor_iec: sym("var_resistor_iec", "Indicators and Lamps", "Variable Resistor", "variable_resistor", 60, 30, {}, "iec"),
  capacitor_iec: sym("capacitor_iec", "Indicators and Lamps", "Capacitor", "capacitor", 40, 60, {}, "iec"),
  inductor_iec: sym("inductor_iec", "Indicators and Lamps", "Inductor", "inductor", 60, 30, {}, "iec"),
  battery_iec: sym("battery_iec", "Power Sources", "Battery Cell", "battery", 40, 50, {}, "iec"),
  battery_pack_iec: sym("battery_pack_iec", "Power Sources", "Battery Pack", "battery_multi", 60, 50, {}, "iec"),
  ground_iec: sym("ground_iec", "Power Sources", "Earth Ground", "ground", 40, 40, {}, "iec"),
  chassis_ground_iec: sym("chassis_ground_iec", "Power Sources", "Chassis Ground", "ground", 40, 40, { label: "Chassis" }, "iec"),
  solar_iec: sym("solar_iec", "Power Sources", "Solar Panel", "solar_panel", 60, 40, {}, "iec"),
  ups_iec: sym("ups_iec", "Power Sources", "UPS System", "ups", 60, 60, {}, "iec"),
  vfd_iec: sym("vfd_iec", "Indicators and Lamps", "VFD Drive", "vfd", 50, 50, {}, "iec"),
  soft_starter_iec: sym("soft_starter_iec", "Indicators and Lamps", "Soft Starter", "vfd", 50, 50, { label: "SoftStart" }, "iec"),
  plc_iec: sym("plc_iec", "Indicators and Lamps", "PLC Mod", "vfd", 60, 60, { label: "PLC" }, "iec"),
  ammeter: sym("ammeter", "Metering", "Ammeter", "ammeter", 40, 40, {}, "iec"),
  voltmeter: sym("voltmeter", "Metering", "Voltmeter", "voltmeter", 40, 40, {}, "iec"),
  wattmeter: sym("wattmeter", "Metering", "Wattmeter", "wattmeter", 40, 40, {}, "iec"),
  hz_meter: sym("hz_meter", "Metering", "Frequency Meter", "frequency_meter", 40, 40, {}, "iec"),
  power_meter: sym("power_meter", "Metering", "Power Meter", "power_meter", 50, 50, {}, "iec"),
  kwh_meter: sym("kwh_meter", "Metering", "Energy Meter", "power_meter", 50, 50, { label: "kWh" }, "iec"),
  multimeter_iec: sym("multimeter_iec", "Metering", "Multimeter", "power_meter", 50, 50, { label: "V A Hz" }, "iec"),
  pf_meter_iec: sym("pf_meter_iec", "Metering", "Cos Phi Meter", "power_meter", 50, 50, { label: "Cosφ" }, "iec"),

  // ==========================================
  // --- ANSI Category (116 items) ---
  // ==========================================
  ansi_contact_no: sym("ansi_contact_no", "Switches and Disconnectors", "Contact NO", "ansi_contact_no", 40, 50, {}, "ansi"),
  ansi_contact_nc: sym("ansi_contact_nc", "Switches and Disconnectors", "Contact NC", "ansi_contact_nc", 40, 50, {}, "ansi"),
  ansi_pushb_no: sym("ansi_pushb_no", "Switches and Disconnectors", "Pushbutton NO", "ansi_pushb_no", 40, 50, {}, "ansi"),
  ansi_pushb_nc: sym("ansi_pushb_nc", "Switches and Disconnectors", "Pushbutton NC", "ansi_pushb_nc", 40, 50, {}, "ansi"),
  ansi_pushb_mush_no: sym("ansi_pushb_mush_no", "Switches and Disconnectors", "PB Mushroom NO", "ansi_pushb_mush_no", 40, 50, {}, "ansi"),
  ansi_pushb_mush_nc: sym("ansi_pushb_mush_nc", "Switches and Disconnectors", "PB Mushroom NC", "ansi_pushb_mush_nc", 40, 50, {}, "ansi"),
  ansi_maintained_no: sym("ansi_maintained_no", "Switches and Disconnectors", "Maintained PB NO", "ansi_pushb_no", 40, 50, { label: "Maint" }, "ansi"),
  ansi_maintained_nc: sym("ansi_maintained_nc", "Switches and Disconnectors", "Maintained PB NC", "ansi_pushb_nc", 40, 50, { label: "Maint" }, "ansi"),
  ansi_limit_sw_no: sym("ansi_limit_sw_no", "Switches and Disconnectors", "Limit Switch NO", "ansi_limit_sw_no", 40, 50, {}, "ansi"),
  ansi_limit_sw_nc: sym("ansi_limit_sw_nc", "Switches and Disconnectors", "Limit Switch NC", "ansi_limit_sw_nc", 40, 50, {}, "ansi"),
  ansi_flow_sw_no: sym("ansi_flow_sw_no", "Switches and Disconnectors", "Flow Switch NO", "ansi_flow_sw_no", 40, 50, {}, "ansi"),
  ansi_flow_sw_nc: sym("ansi_flow_sw_nc", "Switches and Disconnectors", "Flow Switch NC", "ansi_flow_sw_nc", 40, 50, {}, "ansi"),
  ansi_press_sw_no: sym("ansi_press_sw_no", "Switches and Disconnectors", "Pressure Sw NO", "ansi_press_sw_no", 40, 50, {}, "ansi"),
  ansi_press_sw_nc: sym("ansi_press_sw_nc", "Switches and Disconnectors", "Pressure Sw NC", "ansi_press_sw_nc", 40, 50, {}, "ansi"),
  ansi_temp_sw_no: sym("ansi_temp_sw_no", "Switches and Disconnectors", "Temperature Sw NO", "ansi_temp_sw_no", 40, 50, {}, "ansi"),
  ansi_temp_sw_nc: sym("ansi_temp_sw_nc", "Switches and Disconnectors", "Temperature Sw NC", "ansi_temp_sw_nc", 40, 50, {}, "ansi"),
  ansi_level_sw_no: sym("ansi_level_sw_no", "Switches and Disconnectors", "Level Switch NO", "ansi_level_sw_no", 40, 50, {}, "ansi"),
  ansi_level_sw_nc: sym("ansi_level_sw_nc", "Switches and Disconnectors", "Level Switch NC", "ansi_level_sw_nc", 40, 50, {}, "ansi"),
  ansi_foot_sw_no: sym("ansi_foot_sw_no", "Switches and Disconnectors", "Foot Switch NO", "ansi_foot_sw_no", 40, 50, {}, "ansi"),
  ansi_foot_sw_nc: sym("ansi_foot_sw_nc", "Switches and Disconnectors", "Foot Switch NC", "ansi_foot_sw_nc", 40, 50, {}, "ansi"),
  ansi_selector_2p: sym("ansi_selector_2p", "Switches and Disconnectors", "Selector 2-Pos", "selector_switch_2", 40, 50, { label: "Sel2" }, "ansi"),
  ansi_selector_3p: sym("ansi_selector_3p", "Switches and Disconnectors", "Selector 3-Pos", "selector_switch_3", 40, 50, { label: "Sel3" }, "ansi"),
  ansi_key_2p: sym("ansi_key_2p", "Switches and Disconnectors", "Key Switch 2P", "selector_switch_2", 40, 50, { label: "Key" }, "ansi"),
  ansi_tdc_no: sym("ansi_tdc_no", "Switches and Disconnectors", "TDC Contact NO", "ansi_tdc_no", 40, 60, {}, "ansi"),
  ansi_tdc_nc: sym("ansi_tdc_nc", "Switches and Disconnectors", "TDC Contact NC", "ansi_tdc_nc", 40, 60, {}, "ansi"),
  ansi_tdo_no: sym("ansi_tdo_no", "Switches and Disconnectors", "TDO Contact NO", "ansi_tdo_no", 40, 60, {}, "ansi"),
  ansi_tdo_nc: sym("ansi_tdo_nc", "Switches and Disconnectors", "TDO Contact NC", "ansi_tdo_nc", 40, 60, {}, "ansi"),
  ansi_disconnect_1p: sym("ansi_disconnect_1p", "Switches and Disconnectors", "1P Disconnect", "ansi_disconnect", 40, 60, {}, "ansi"),
  ansi_disconnect_2p: sym("ansi_disconnect_2p", "Switches and Disconnectors", "2P Disconnect", "ansi_disconnect", 50, 60, { label: "2P" }, "ansi"),
  ansi_disconnect_3p: sym("ansi_disconnect_3p", "Switches and Disconnectors", "3P Disconnect", "ansi_disconnect", 60, 60, { label: "3P" }, "ansi"),
  ansi_disconnect_4p: sym("ansi_disconnect_4p", "Switches and Disconnectors", "4P Disconnect", "ansi_disconnect", 70, 60, { label: "4P" }, "ansi"),
  ansi_fused_disc_3p: sym("ansi_fused_disc_3p", "Switches and Disconnectors", "3P Fused Disc.", "ansi_disconnect", 60, 60, { label: "Fused" }, "ansi"),
  ansi_cb_1p: sym("ansi_cb_1p", "Breakers and Protection", "1P Circuit Breaker", "ansi_circuit_breaker", 40, 60, {}, "ansi"),
  ansi_cb_2p: sym("ansi_cb_2p", "Breakers and Protection", "2P Circuit Breaker", "ansi_cb_3p", 50, 60, { label: "2P" }, "ansi"),
  ansi_cb_3p: sym("ansi_cb_3p", "Breakers and Protection", "3P Circuit Breaker", "ansi_cb_3p", 60, 60, {}, "ansi"),
  ansi_cb_4p: sym("ansi_cb_4p", "Breakers and Protection", "4P Circuit Breaker", "ansi_cb_3p", 70, 60, { label: "4P" }, "ansi"),
  ansi_cb_mccb: sym("ansi_cb_mccb", "Breakers and Protection", "MCCB (ANSI)", "ansi_cb_3p", 60, 60, { label: "MCCB" }, "ansi"),
  ansi_cb_acb: sym("ansi_cb_acb", "Breakers and Protection", "ACB (ANSI)", "ansi_cb_3p", 70, 70, { label: "ACB" }, "ansi"),
  ansi_cb_drawout: sym("ansi_cb_drawout", "Breakers and Protection", "Drawout CB", "ansi_cb_3p", 70, 60, { label: "Drawout" }, "ansi"),
  ansi_fuse_1p: sym("ansi_fuse_1p", "Fuses", "1P Fuse", "ansi_fuse", 20, 60, {}, "ansi"),
  ansi_fuse_2p: sym("ansi_fuse_2p", "Fuses", "2P Fuse", "ansi_fuse", 30, 60, { label: "2P" }, "ansi"),
  ansi_fuse_3p: sym("ansi_fuse_3p", "Fuses", "3P Fuse", "ansi_fuse", 40, 60, { label: "3P" }, "ansi"),
  ansi_dropout_fuse: sym("ansi_dropout_fuse", "Fuses", "Dropout Fuse", "ansi_fuse", 30, 70, { label: "DO" }, "ansi"),
  ansi_expulsion_fuse: sym("ansi_expulsion_fuse", "Fuses", "Expulsion Fuse", "ansi_fuse", 30, 70, { label: "Expulsion" }, "ansi"),
  ansi_current_limit_fuse: sym("ansi_current_limit_fuse", "Fuses", "Curr. Limiting", "ansi_fuse", 30, 70, { label: "CLF" }, "ansi"),
  ansi_coil: sym("ansi_coil", "Relays and Contactors", "Operating Coil", "ansi_relay_coil", 40, 40, {}, "ansi"),
  ansi_coil_latch: sym("ansi_coil_latch", "Relays and Contactors", "Latch Coil", "ansi_coil_latch", 40, 40, {}, "ansi"),
  ansi_coil_unlatch: sym("ansi_coil_unlatch", "Relays and Contactors", "Unlatch Coil", "ansi_coil_unlatch", 40, 40, {}, "ansi"),
  ansi_coil_timer: sym("ansi_coil_timer", "Relays and Contactors", "Timer Coil", "ansi_coil_timer", 40, 40, {}, "ansi"),
  ansi_overload_1p: sym("ansi_overload_1p", "Relays and Contactors", "1P Overload Heater", "ansi_overload", 40, 40, {}, "ansi"),
  ansi_overload_3p: sym("ansi_overload_3p", "Relays and Contactors", "3P Overload Heater", "ansi_overload", 60, 40, { label: "3P" }, "ansi"),
  ansi_contactor_1p: sym("ansi_contactor_1p", "Relays and Contactors", "1P Contactor", "ansi_contactor", 40, 50, {}, "ansi"),
  ansi_contactor_3p: sym("ansi_contactor_3p", "Relays and Contactors", "3P Contactor", "ansi_contactor", 60, 50, { label: "3P" }, "ansi"),
  ansi_relay_50: sym("ansi_relay_50", "Relays and Contactors", "Inst. OC (50)", "ansi_relay_coil", 50, 50, { label: "50" }, "ansi"),
  ansi_relay_51: sym("ansi_relay_51", "Relays and Contactors", "Time OC (51)", "ansi_relay_coil", 50, 50, { label: "51" }, "ansi"),
  ansi_relay_27: sym("ansi_relay_27", "Relays and Contactors", "Undervoltage (27)", "ansi_relay_coil", 50, 50, { label: "27" }, "ansi"),
  ansi_relay_59: sym("ansi_relay_59", "Relays and Contactors", "Overvoltage (59)", "ansi_relay_coil", 50, 50, { label: "59" }, "ansi"),
  ansi_relay_87: sym("ansi_relay_87", "Relays and Contactors", "Differential (87)", "ansi_relay_coil", 50, 50, { label: "87" }, "ansi"),
  ansi_relay_86: sym("ansi_relay_86", "Relays and Contactors", "Lockout (86)", "ansi_relay_coil", 50, 50, { label: "86" }, "ansi"),
  ansi_relay_81: sym("ansi_relay_81", "Relays and Contactors", "Frequency (81)", "ansi_relay_coil", 50, 50, { label: "81" }, "ansi"),
  ansi_relay_32: sym("ansi_relay_32", "Relays and Contactors", "Power Dir (32)", "ansi_relay_coil", 50, 50, { label: "32" }, "ansi"),
  ansi_relay_49: sym("ansi_relay_49", "Relays and Contactors", "Thermal (49)", "ansi_relay_coil", 50, 50, { label: "49" }, "ansi"),
  ansi_trans_1p: sym("ansi_trans_1p", "Transformers", "1P Transformer", "ansi_transformer", 50, 80, {}, "ansi"),
  ansi_trans_3p: sym("ansi_trans_3p", "Transformers", "3P Transformer", "ansi_trans_3p", 70, 80, {}, "ansi"),
  ansi_trans_3p_yy: sym("ansi_trans_3p_yy", "Transformers", "3P Trafo (Y-Y)", "ansi_trans_3p", 70, 80, { label: "Y-Y" }, "ansi"),
  ansi_trans_3p_yd: sym("ansi_trans_3p_yd", "Transformers", "3P Trafo (Y-Delta)", "ansi_trans_3p", 70, 80, { label: "Y-D" }, "ansi"),
  ansi_trans_3p_dd: sym("ansi_trans_3p_dd", "Transformers", "3P Trafo (Delta-Delta)", "ansi_trans_3p", 70, 80, { label: "D-D" }, "ansi"),
  ansi_trans_zig: sym("ansi_trans_zig", "Transformers", "Zig-Zag Ground", "ansi_trans_3p", 70, 80, { label: "Zig-Zag" }, "ansi"),
  ansi_auto_trans: sym("ansi_auto_trans", "Transformers", "Auto Transformer", "ansi_auto_trans", 50, 80, {}, "ansi"),
  ansi_pt_1p: sym("ansi_pt_1p", "Transformers", "1P Pot. Transformer", "ansi_pt", 50, 50, {}, "ansi"),
  ansi_pt_3p: sym("ansi_pt_3p", "Transformers", "3P Pot. Transformer", "ansi_pt", 60, 50, { label: "3P" }, "ansi"),
  ansi_ct_1p: sym("ansi_ct_1p", "Transformers", "1P Cur. Transformer", "ansi_ct", 40, 40, {}, "ansi"),
  ansi_ct_3p: sym("ansi_ct_3p", "Transformers", "3P Cur. Transformer", "ansi_ct", 60, 40, { label: "3P" }, "ansi"),
  ansi_ct_multi: sym("ansi_ct_multi", "Transformers", "Multi-ratio CT", "ansi_ct", 50, 40, { label: "MR" }, "ansi"),
  ansi_motor_1p: sym("ansi_motor_1p", "Motors and Generators", "1P Motor", "ansi_motor", 50, 50, {}, "ansi"),
  ansi_motor_3p: sym("ansi_motor_3p", "Motors and Generators", "3P Motor", "ansi_motor", 60, 60, { label: "3P" }, "ansi"),
  ansi_motor_synp: sym("ansi_motor_synp", "Motors and Generators", "Sync Motor", "ansi_motor", 60, 60, { label: "Sync" }, "ansi"),
  ansi_gen_1p: sym("ansi_gen_1p", "Motors and Generators", "1P Generator", "ansi_generator", 50, 50, {}, "ansi"),
  ansi_gen_3p: sym("ansi_gen_3p", "Motors and Generators", "3P Generator", "ansi_generator", 60, 60, { label: "3P" }, "ansi"),
  ansi_resistor: sym("ansi_resistor", "Indicators and Lamps", "Resistor", "ansi_resistor", 60, 20, {}, "ansi"),
  ansi_var_resistor: sym("ansi_var_resistor", "Indicators and Lamps", "Variable Resistor", "ansi_resistor", 60, 20, { label: "Var" }, "ansi"),
  ansi_capacitor: sym("ansi_capacitor", "Indicators and Lamps", "Capacitor", "ansi_capacitor", 40, 60, {}, "ansi"),
  ansi_inductor: sym("ansi_inductor", "Indicators and Lamps", "Inductor", "ansi_inductor", 60, 20, {}, "ansi"),
  ansi_lamp: sym("ansi_lamp", "Indicators and Lamps", "Indicator Lamp", "ansi_lamp", 40, 40, {}, "ansi"),
  ansi_lamp_red: sym("ansi_lamp_red", "Indicators and Lamps", "Red Lamp", "ansi_lamp", 40, 40, { label: "R" }, "ansi"),
  ansi_lamp_green: sym("ansi_lamp_green", "Indicators and Lamps", "Green Lamp", "ansi_lamp", 40, 40, { label: "G" }, "ansi"),
  ansi_lamp_amber: sym("ansi_lamp_amber", "Indicators and Lamps", "Amber Lamp", "ansi_lamp", 40, 40, { label: "A" }, "ansi"),
  ansi_lamp_blue: sym("ansi_lamp_blue", "Indicators and Lamps", "Blue Lamp", "ansi_lamp", 40, 40, { label: "B" }, "ansi"),
  ansi_lamp_white: sym("ansi_lamp_white", "Indicators and Lamps", "White Lamp", "ansi_lamp", 40, 40, { label: "W" }, "ansi"),
  ansi_horn: sym("ansi_horn", "Indicators and Lamps", "Horn / Alarm", "ansi_horn", 40, 40, {}, "ansi"),
  ansi_bell: sym("ansi_bell", "Indicators and Lamps", "Bell", "ansi_bell", 40, 40, {}, "ansi"),
  ansi_siren: sym("ansi_siren", "Indicators and Lamps", "Siren", "ansi_horn", 40, 40, { label: "Siren" }, "ansi"),
  ansi_ground: sym("ansi_ground", "Power Sources", "Earth Ground", "ansi_ground", 40, 40, {}, "ansi"),
  ansi_chassis: sym("ansi_chassis", "Power Sources", "Chassis Ground", "ansi_ground", 40, 40, { label: "Chassis" }, "ansi"),
  ansi_ammeter: sym("ansi_ammeter", "Metering", "Ammeter", "ammeter", 40, 40, {}, "ansi"),
  ansi_voltmeter: sym("ansi_voltmeter", "Metering", "Voltmeter", "voltmeter", 40, 40, {}, "ansi"),
  ansi_wattmeter: sym("ansi_wattmeter", "Metering", "Wattmeter", "wattmeter", 40, 40, {}, "ansi"),
  ansi_varmeter: sym("ansi_varmeter", "Metering", "VAR Meter", "wattmeter", 40, 40, { label: "VAR" }, "ansi"),
  ansi_pfa: sym("ansi_pfa", "Metering", "Power Factor Meter", "wattmeter", 50, 40, { label: "PF" }, "ansi"),
  ansi_hz_meter: sym("ansi_hz_meter", "Metering", "Freq Meter", "frequency_meter", 40, 40, {}, "ansi"),
  ansi_demand: sym("ansi_demand", "Metering", "Demand Meter", "power_meter", 50, 50, { label: "Demand" }, "ansi"),
  ansi_kwh: sym("ansi_kwh", "Metering", "kWh Meter", "power_meter", 50, 50, { label: "kWh" }, "ansi"),
  
}; // END OF SYMBOL_REGISTRY // Total 306 Items

export const symbolRegistry = SYMBOL_REGISTRY;
